version: '3' 
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_docker
    ports:
      - 8090:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: wordpress_docker_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db
    ports:
      - 8890:80

  db: 
    image: mysql:5.7
    container_name: wordpress_docker_mysql
    ports:
      - 13307:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log/:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      TZ: Asia/Tokyo
